import 'watch.dart';
import 'review.dart';
import 'order.dart';
import 'cart_item.dart';
import 'user_profile.dart';
import 'chat_message.dart';

class MockData {
  static final UserProfile defaultUser = UserProfile(
    id: 'usr_001',
    name: 'Alexander Vance',
    email: 'alexander.vance@watchhub.com',
    phone: '+1 (555) 382-9901',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    shippingAddresses: [
      '742 Evergreen Terrace, Suite 4B, New York, NY 10021',
      '88 Ocean Drive, Penthouse 12, Miami, FL 33139',
    ],
    defaultAddress: '742 Evergreen Terrace, Suite 4B, New York, NY 10021',
    isAdmin: false,
    loyaltyPoints: 750,
    vipStatus: 'Gold',
    unlockedBadges: ['Horology Enthusiast', 'Bespoke Creator'],
    savedCards: [
      {'number': '•••• 8812', 'type': 'Amex', 'expiry': '12/29'},
      {'number': '•••• 4920', 'type': 'Visa', 'expiry': '08/28'},
    ],
  );

  static final List<String> categories = [
    'All',
    'Luxury',
    'Chronograph',
    'Diver',
    'Dress',
    'Smart',
  ];

  static final List<String> brands = [
    'Rolex',
    'Omega',
    'Patek Philippe',
    'Audemars Piguet',
    'Tag Heuer',
    'Cartier',
    'IWC',
    'Breitling',
    'Vacheron Constantin',
    'Apple',
  ];

  static final List<Watch> watches = [
    Watch(
      id: 'w_001',
      title: 'Cosmograph Daytona Platinum',
      brand: 'Rolex',
      price: 34500.0,
      originalPrice: 38000.0,
      rating: 4.9,
      reviewCount: 128,
      imageUrls: [
        'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Luxury',
      type: 'Automatic Chronograph',
      description:
          'The benchmark for those with a passion for driving and speed. Features an ice blue dial, chestnut brown Cerachrom bezel, and platinum oyster case with self-winding Calibre 4130.',
      specifications: {
        'Movement': 'Self-winding Calibre 4130',
        'Case Material': '950 Platinum',
        'Case Diameter': '40 mm',
        'Water Resistance': '100m / 330 ft',
        'Dial Color': 'Ice Blue with Chestnut Bezel',
        'Strap': 'Oyster, three-piece solid links',
        'Power Reserve': 'Approximately 72 hours',
      },
      availableColors: ['Ice Blue', 'Slate Grey', 'Classic Black'],
      availableStraps: ['Oyster Platinum', 'Alligator Leather'],
      stockCount: 4,
      isPopular: true,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_002',
      title: 'Speedmaster Professional Moonwatch',
      brand: 'Omega',
      price: 7600.0,
      originalPrice: 8200.0,
      rating: 4.8,
      reviewCount: 94,
      imageUrls: [
        'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Chronograph',
      type: 'Manual Wind',
      description:
          'The Legendary Moonwatch tested by NASA on all six lunar missions. Equipped with the Master Chronometer Calibre 3861 for incredible magnetic resistance and precision.',
      specifications: {
        'Movement': 'Omega Calibre 3861',
        'Case Material': 'Stainless Steel',
        'Case Diameter': '42 mm',
        'Water Resistance': '50m / 167 ft',
        'Dial Color': 'Matte Black',
        'Strap': 'Steel Bracelet / NATO Nylon',
        'Power Reserve': '50 hours',
      },
      availableColors: ['Matte Black', 'Silver Opalescent'],
      availableStraps: ['Steel Bracelet', 'Nylon NATO', 'Leather Calfskin'],
      stockCount: 8,
      isPopular: true,
      isFeatured: true,
      isNewArrival: false,
    ),
    Watch(
      id: 'w_003',
      title: 'Nautilus Self-Winding Rose Gold',
      brand: 'Patek Philippe',
      price: 52000.0,
      originalPrice: 55000.0,
      rating: 5.0,
      reviewCount: 62,
      imageUrls: [
        'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Luxury',
      type: 'Automatic',
      description:
          'With the iconic octagonal bezel and horizontal embossed dial, the Nautilus has personified the elegant sports watch since 1976.',
      specifications: {
        'Movement': 'Calibre 26-330 S C',
        'Case Material': '18K Rose Gold',
        'Case Diameter': '40.5 mm',
        'Water Resistance': '120m',
        'Dial Color': 'Rose Gold Brown Sunburst',
        'Strap': 'Rose Gold Bracelet with Fold-over Clasp',
        'Power Reserve': '45 hours',
      },
      availableColors: ['Rose Gold', 'Olive Green', 'Classic Blue'],
      availableStraps: ['Rose Gold Link', 'Chocolate Rubber'],
      stockCount: 2,
      isPopular: true,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_004',
      title: 'Royal Oak Offshore Diver',
      brand: 'Audemars Piguet',
      price: 28900.0,
      originalPrice: null,
      rating: 4.7,
      reviewCount: 45,
      imageUrls: [
        'https://images.unsplash.com/photo-1619134778706-7015533a6150?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Diver',
      type: 'Automatic',
      description:
          'Designed for high-impact marine exploration with Méga Tapisserie pattern, sapphire crystal glareproofed case back, and quick-change rubber strap.',
      specifications: {
        'Movement': 'Calibre 4308',
        'Case Material': 'Stainless Steel & Ceramic',
        'Case Diameter': '42 mm',
        'Water Resistance': '300m / 1000 ft',
        'Dial Color': 'Khaki Green',
        'Strap': 'Textured Green Rubber',
        'Power Reserve': '60 hours',
      },
      availableColors: ['Khaki Green', 'Marine Blue', 'Stealth Black'],
      availableStraps: ['Green Rubber', 'Black Rubber'],
      stockCount: 5,
      isPopular: false,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_005',
      title: 'Monaco Calibre 11 Special Edition',
      brand: 'Tag Heuer',
      price: 6850.0,
      originalPrice: 7400.0,
      rating: 4.6,
      reviewCount: 81,
      imageUrls: [
        'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Chronograph',
      type: 'Automatic',
      description:
          'The original square-faced icon worn by Steve McQueen in Le Mans. Featuring left-hand crown, metallic blue dial, and silver sub-dials.',
      specifications: {
        'Movement': 'Tag Heuer Calibre 11 Automatic',
        'Case Material': 'Fine-brushed Steel',
        'Case Diameter': '39 mm',
        'Water Resistance': '100m',
        'Dial Color': 'Metallic Blue',
        'Strap': 'Black Calfskin Leather with Racing Perforations',
        'Power Reserve': '40 hours',
      },
      availableColors: ['Monaco Blue', 'Gulf Racing Stripes'],
      availableStraps: ['Perforated Leather', 'Steel Link'],
      stockCount: 10,
      isPopular: true,
      isFeatured: false,
      isNewArrival: false,
    ),
    Watch(
      id: 'w_006',
      title: 'Santos de Cartier Large Model',
      brand: 'Cartier',
      price: 8100.0,
      originalPrice: null,
      rating: 4.9,
      reviewCount: 110,
      imageUrls: [
        'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Dress',
      type: 'Automatic',
      description:
          'Created in 1904 for aviator Alberto Santos-Dumont. Features QuickSwitch interchangeable strap technology and SmartLink size adjustment system.',
      specifications: {
        'Movement': 'Manufacture Calibre 1847 MC',
        'Case Material': 'Steel & ADLC Bezel',
        'Case Diameter': '39.8 mm',
        'Water Resistance': '100m',
        'Dial Color': 'Silvered Opaline',
        'Strap': 'Interchangeable Steel & Calfskin',
        'Power Reserve': '42 hours',
      },
      availableColors: ['Silvered Opaline', 'ADLC Black'],
      availableStraps: ['Steel SmartLink', 'Tan Calfskin Leather'],
      stockCount: 7,
      isPopular: true,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_007',
      title: 'Summit 3 Smartwatch Titanium Edition',
      brand: 'Tag Heuer',
      price: 2450.0,
      originalPrice: 2800.0,
      rating: 4.5,
      reviewCount: 38,
      imageUrls: [
        'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Smart',
      type: 'WearOS Ultra',
      description:
          'Luxury smart companion crafted in grade 5 titanium with custom sapphire display crystal, health heart-rate sensors, and GPS navigation.',
      specifications: {
        'Processor': 'Snapdragon Wear 4100+',
        'Case Material': 'Grade 5 Titanium',
        'Display': '1.28" AMOLED Sapphire Crystal',
        'Water Resistance': '50m / 5 ATM',
        'Sensors': 'Heart rate, SpO2, Barometer, GPS, NFC',
        'Battery Life': 'All-Day Performance Mode',
      },
      availableColors: ['Titanium Grey', 'DLC Jet Black'],
      availableStraps: ['Sport Rubber', 'Hand-stitched Leather'],
      stockCount: 15,
      isPopular: false,
      isFeatured: false,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_008',
      title: 'Submariner Date "Kermit"',
      brand: 'Rolex',
      price: 14500.0,
      originalPrice: 15800.0,
      rating: 4.9,
      reviewCount: 142,
      imageUrls: [
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Diver',
      type: 'Automatic',
      description:
          'The ultimate divers watch. Features a green Cerachrom bezel, black dial, large luminescent hour markers, and signature Oystersteel bracelet.',
      specifications: {
        'Movement': 'Self-winding Calibre 3235',
        'Case Material': 'Oystersteel',
        'Case Diameter': '41 mm',
        'Water Resistance': '300m / 1000 ft',
        'Dial Color': 'Classic Black with Green Bezel',
        'Strap': 'Oystersteel Flat Three-piece',
        'Power Reserve': 'Approximately 70 hours',
      },
      availableColors: ['Green Bezel Black Dial', 'Full Jet Black'],
      availableStraps: ['Oystersteel Bracelet', 'Stealth Rubber'],
      stockCount: 5,
      isPopular: true,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_009',
      title: 'Grand Complications Perpetual',
      brand: 'Patek Philippe',
      price: 89000.0,
      originalPrice: 95000.0,
      rating: 5.0,
      reviewCount: 29,
      imageUrls: [
        'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Luxury',
      type: 'Manual Wind Mechanical',
      description:
          'An extraordinary creation featuring a perpetual calendar, moon phases, day, date, month, leap year, and 24-hour indication in a stunning white gold case.',
      specifications: {
        'Movement': 'Manual Wind Calibre CH 29-535 PS Q',
        'Case Material': '18K White Gold',
        'Case Diameter': '41 mm',
        'Water Resistance': '30m / 100 ft',
        'Dial Color': 'Blue Lacquered Sunburst',
        'Strap': 'Navy Blue Alligator Leather',
        'Power Reserve': 'Approximately 65 hours',
      },
      availableColors: ['Blue Sunburst', 'Silver Opaline'],
      availableStraps: ['Alligator Leather', 'Black Matte Leather'],
      stockCount: 1,
      isPopular: false,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_010',
      title: 'Portugieser Chronograph Classic',
      brand: 'IWC',
      price: 8400.0,
      originalPrice: null,
      rating: 4.7,
      reviewCount: 56,
      imageUrls: [
        'https://images.unsplash.com/photo-1619134778706-7015533a6150?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Chronograph',
      type: 'Automatic Chronograph',
      description:
          'One of the most famous timepieces from Schaffhausen. Elegant design featuring blue Arabic numerals, slim feuille hands, and precise quarter-second scale.',
      specifications: {
        'Movement': 'IWC Calibre 69355',
        'Case Material': 'Stainless Steel',
        'Case Diameter': '41 mm',
        'Water Resistance': '30m',
        'Dial Color': 'Silver-plated with Blue Hands',
        'Strap': 'Blue Alligator Leather by Santoni',
        'Power Reserve': '46 hours',
      },
      availableColors: ['Silver-plated Blue', 'Intense Black'],
      availableStraps: ['Alligator Leather', 'Steel Mesh Bracelet'],
      stockCount: 4,
      isPopular: true,
      isFeatured: false,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_011',
      title: 'Overseas Automatic Blue Dial',
      brand: 'Vacheron Constantin',
      price: 22500.0,
      originalPrice: 24500.0,
      rating: 4.8,
      reviewCount: 73,
      imageUrls: [
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Luxury',
      type: 'Automatic',
      description:
          'Dedicated to the spirit of travel and exploration. Features the iconic six-sided bezel inspired by the Maltese cross, and blue dial with translucent lacquer.',
      specifications: {
        'Movement': 'Manufacture Calibre 5100',
        'Case Material': 'Stainless Steel',
        'Case Diameter': '41 mm',
        'Water Resistance': '150m / 500 ft',
        'Dial Color': 'Translucent Blue Lacquered',
        'Strap': 'Interchangeable Steel, Rubber & Alligator',
        'Power Reserve': '60 hours',
      },
      availableColors: ['Lacquered Blue', 'Slate Grey'],
      availableStraps: ['Stainless Steel Bracelet', 'Blue Rubber Strap', 'Alligator Leather'],
      stockCount: 3,
      isPopular: true,
      isFeatured: true,
      isNewArrival: true,
    ),
    Watch(
      id: 'w_012',
      title: 'Watch Ultra 2 Adventure',
      brand: 'Apple',
      price: 799.0,
      originalPrice: null,
      rating: 4.8,
      reviewCount: 48,
      imageUrls: [
        'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Smart',
      type: 'Smartwatch',
      description:
          'The most rugged and capable watch ever. Featuring a lightweight aerospace-grade titanium case, up to 36-hour battery life, and high-precision dual-frequency GPS.',
      specifications: {
        'Processor': 'Apple S9 SiP',
        'Case Material': 'Grade 5 Aerospace Titanium',
        'Display': 'Always-On Retina display, 3000 nits',
        'Water Resistance': '100m / Swimproof & Recreational Dive',
        'Sensors': 'Depth gauge, Water temp, ECG, Blood Oxygen',
        'Battery Life': 'Up to 36 hours (72 hours in low power)',
      },
      availableColors: ['Titanium Natural', 'Satin Black'],
      availableStraps: ['Ocean Band', 'Trail Loop', 'Alpine Loop'],
      stockCount: 20,
      isPopular: false,
      isFeatured: false,
      isNewArrival: true,
    ),
  ];

  static final List<Review> sampleReviews = [
    Review(
      id: 'rev_1',
      watchId: 'w_001',
      userName: 'Julian Thorne',
      userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
      rating: 5.0,
      comment:
          'Absolute masterwork of horology. The platinum weight feels substantial yet perfectly balanced on the wrist. Delivery was secured within 24 hours in a heavy hardwood presentation box.',
      date: DateTime.now().subtract(const Duration(days: 3)),
      helpfulCount: 24,
      isVerifiedPurchase: true,
    ),
    Review(
      id: 'rev_2',
      watchId: 'w_001',
      userName: 'Elena Rostova',
      userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
      rating: 4.8,
      comment:
          'The ice blue dial under natural sunlight is unmatched. WatchHub white-glove support provided instant verification documents.',
      date: DateTime.now().subtract(const Duration(days: 12)),
      helpfulCount: 15,
      isVerifiedPurchase: true,
    ),
    Review(
      id: 'rev_3',
      watchId: 'w_002',
      userName: 'Marcus Brody',
      userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
      rating: 5.0,
      comment:
          'An absolute essential for any serious collector. The manual winding routine every morning connects you to space history.',
      date: DateTime.now().subtract(const Duration(days: 7)),
      helpfulCount: 19,
      isVerifiedPurchase: true,
    ),
  ];

  static final List<Order> sampleOrders = [
    Order(
      id: 'WH-9082-2026',
      orderDate: DateTime.now().subtract(const Duration(days: 2)),
      items: [
        CartItem(
          watch: watches[1],
          selectedColor: 'Matte Black',
          selectedStrap: 'Steel Bracelet',
          quantity: 1,
        ),
      ],
      subtotal: 7600.0,
      tax: 608.0,
      shippingFee: 0.0,
      totalAmount: 8208.0,
      shippingAddress: '742 Evergreen Terrace, Suite 4B, New York, NY 10021',
      paymentMethod: 'Apple Pay (•••• 4921)',
      status: OrderStatus.shipped,
      trackingSteps: [
        TrackingStep(
          title: 'Order Placed & Payment Verified',
          description: 'Payment authorized via Apple Pay.',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 4)),
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Master Horologist Inspection',
          description: 'Multi-point timing test and authenticity seal certified.',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 14)),
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Dispatched with Armored Courier',
          description: 'FedEx Priority Overnight Express - Tracking #98230194821',
          timestamp: DateTime.now().subtract(const Duration(hours: 8)),
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Out for Delivery',
          description: 'Courier assigned to local delivery vehicle.',
          timestamp: DateTime.now().add(const Duration(hours: 14)),
          isCompleted: false,
        ),
        TrackingStep(
          title: 'Delivered',
          description: 'Signature required upon receipt.',
          timestamp: DateTime.now().add(const Duration(hours: 20)),
          isCompleted: false,
        ),
      ],
    ),
    Order(
      id: 'WH-7410-2026',
      orderDate: DateTime.now().subtract(const Duration(days: 45)),
      items: [
        CartItem(
          watch: watches[5],
          selectedColor: 'Silvered Opaline',
          selectedStrap: 'Steel SmartLink',
          quantity: 1,
        ),
      ],
      subtotal: 8100.0,
      tax: 648.0,
      shippingFee: 0.0,
      totalAmount: 8748.0,
      shippingAddress: '88 Ocean Drive, Penthouse 12, Miami, FL 33139',
      paymentMethod: 'Visa Ending in 8812',
      status: OrderStatus.delivered,
      trackingSteps: [
        TrackingStep(
          title: 'Order Placed',
          description: 'Order confirmed.',
          timestamp: DateTime.now().subtract(const Duration(days: 45)),
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Inspected',
          description: 'Quality pass confirmed.',
          timestamp: DateTime.now().subtract(const Duration(days: 44)),
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Delivered',
          description: 'Delivered to resident.',
          timestamp: DateTime.now().subtract(const Duration(days: 43)),
          isCompleted: true,
        ),
      ],
    ),
  ];

  static final List<FAQItem> faqs = [
    FAQItem(
      question: 'Are all watches sold on WatchHub 100% authentic?',
      answer:
          'Yes. Every timepiece in our inventory undergoes rigorous multi-point verification by certified master horologists, complete with original manufacturer papers and WatchHub digital certificate of authenticity.',
      category: 'Authenticity',
    ),
    FAQItem(
      question: 'What is your warranty policy?',
      answer:
          'All timepieces purchased through WatchHub include a complimentary 2-Year International WatchHub Concierge Warranty in addition to remaining factory warranty.',
      category: 'Warranty & Repairs',
    ),
    FAQItem(
      question: 'How does shipping and delivery work?',
      answer:
          'We ship all orders via fully insured Armored Courier Overnight Express. A signature is strictly required upon delivery.',
      category: 'Shipping',
    ),
    FAQItem(
      question: 'Can I return or exchange a watch?',
      answer:
          'We accept returns within 14 days of receipt, provided the watch is unworn, in original condition with intact protective stickers and packaging.',
      category: 'Returns',
    ),
  ];

  static final List<ChatMessage> initialChatMessages = [
    ChatMessage(
      id: 'c_01',
      sender: 'support',
      message:
          'Welcome to WatchHub Concierge! How can our watch specialists assist you today?',
      timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
      options: [
        'Track my order status',
        'Verify watch authenticity',
        'Inquire about trade-ins',
        'Speak to a human specialist',
      ],
    ),
  ];
}
